name: Everyday-Luck
version: '${version}'
main: com.thynanami.plugin.everydayluck.PluginMain
api-version: '1.20'
authors: ["Nanami Nakano"]
description: Simple plugin to generate a luck point(0 - 100) for each player everyday
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0

commands:
  luck:
    description: Get your luck point
    usage: /luck